# AGENTS.md - {{PROJECT_NAME}} Instructions

> Auto-generated by `ai-assist-bootstrap` on {{GENERATED_DATE}}
> Profile: {{STACK_PROFILE}} ({{STACK_TITLE}})
> Target Agents: Claude Code, Cursor, Antigravity, GitHub Copilot, Windsurf

---

## 1. Core Project Invariants
- **Stack**: {{STACK_SUMMARY}}
- **Package / Build Tool**: `{{PACKAGE_MANAGER}}`
- **Strict Boundaries**: Follow the established architectural layout. Do not bypass layer encapsulation.
- **Verification First**: Verify all changes with the test and linter suite before marking tasks as complete.

---

## 2. Essential Commands
- **Install Dependencies**: `{{INSTALL_CMD}}`
- **Start Development**: `{{DEV_CMD}}`
- **Run Tests**: `{{TEST_CMD}}`
- **Lint & Format**: `{{LINT_CMD}}`
- **Type Check**: `{{TYPECHECK_CMD}}`
- **Build Production**: `{{BUILD_CMD}}`

---

## 3. Architecture & Code Layout
```
{{DIRECTORY_TREE}}
```

---

## 4. Key Rules & Constraints
{{STACK_RULES}}

---

## 5. Workflows & Quality Gates
- **Plan Before Code**: For any non-trivial changes, outline a phased plan before modifying files.
- **Quality Check Gate**: All tests (`{{TEST_CMD}}`) and linters (`{{LINT_CMD}}`) must pass with zero errors before commits.
- **Commits**: Format commits with Conventional Commits (`feat:`, `fix:`, `refactor:`, `test:`, `docs:`, `chore:`).
- **Secrets**: NEVER commit `.env*`, API keys, tokens, or credentials.

